apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: DS_PROMETHEUS
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: true

- name: Loki
  type: loki
  uid: DS_LOKI
  access: proxy
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
