{
 "title": "Domino Latest New",
 "description": "HCL Domino Dashboard",
 "tags": [
  "linux",
  "domino"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Domino SAI",
   "type": "gauge",
   "description": "Domino Server Availability Index",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Server_AvailabilityIndex{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "gauge",
   "description": "Domino I/O",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Platform_LogicalDisk_1_PctUtil{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Dead Mail",
   "type": "stat",
   "description": "Mail Dead for all mail.boxes",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Mail_Dead{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Pending Mail",
   "type": "stat",
   "description": "Mail Pending for all mail.boxes",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Mail_TotalPending{instance=\"$node\",job=\"$job\"} - Domino_Mail_Dead{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Certs",
   "type": "stat",
   "description": "CertMgr Certificates",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_CertMgr_CertStatus_Green{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "description": "CertMgr Warnings",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_CertMgr_CertStatus_Yellow{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "CertMgr Errors",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_CertMgr_CertStatus_Red{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Tran/Min",
   "type": "stat",
   "description": "Transactions per Minute",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Server_Trans_PerMinute{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "NSF",
   "type": "stat",
   "description": "Buffer Pool Percent Read in Buffer Pool",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Database_Database_BufferPool_PerCentReadsInBuffer{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "description": "Total cached memory",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes {instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%",
   "type": "stat",
   "description": "Total cached memory in %",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes*100/node_memory_MemTotal_bytes {instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "description": "Percent used RAM",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Mem_Allocated{instance=\"$node\",job=\"$job\"}/Domino_Mem_PhysicalRAM{instance=\"$node\",job=\"$job\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Shared %",
   "type": "gauge",
   "description": "Shared memory in percent",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Domino_Mem_Shared_Used_MB{instance=\"$node\",job=\"$job\"}/Domino_Mem_PhysicalRAM_MB{instance=\"$node\",job=\"$job\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "description": "Transactions per Minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Domino_Server_Trans_PerMinute {instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Domino Server Availability Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "Domino_Server_AvailabilityIndex",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}