{
 "title": "Domino Transactions",
 "description": "HCL Domino Transactions Example",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "increase_interval", "label": "increase_interval", "query": "6m" }
  ]
 },
 "panels": [
  {
   "title": "Transaction/Min",
   "type": "timeseries",
   "description": "Transaction/Min",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(DominoTrans_count{instance=\"$node\",job=\"$job\"}[$increase_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction/Min",
   "type": "timeseries",
   "description": "Transaction/Min",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(DominoTrans_count{instance=\"$node\",job=\"$job\"}[$increase_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "timeseries",
   "description": "Avg Response Time",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(DominoTrans_total_ms[30m]) / rate(DominoTrans_count[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "description": "Transactions per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "Domino_Server_Trans_PerMinute{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GETNOTES_RQST/Min",
   "type": "timeseries",
   "description": "GETNOTES_RQST/Min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "irate(DominoTrans_count{instance=\"$node\",job=\"$job\", op=\"GETNOTES_RQST\"}[$increase_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OPEN_NOTE/Min",
   "type": "timeseries",
   "description": "OPEN_NOTE/Min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(DominoTrans_count{instance=\"$node\",job=\"$job\", op=\"OPEN_NOTE\"}[$increase_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}