{
 "title": "Domino SAI & Transactions",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Domino Server Availability Index",
   "type": "timeseries",
   "description": "Domino Server Expansion Factor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Domino_Server_AvailabilityIndex{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "description": "Transactions per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "Domino_Server_Trans_PerMinute{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Average Time",
   "type": "timeseries",
   "description": "Running Average Time",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(DominoTrans{instance=\"$node\",job=\"$job\",stat=\"count\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Average Time",
   "type": "timeseries",
   "description": "Running Average Time",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(DominoTrans{instance=\"$node\",job=\"$job\",stat=\"count\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}